### ISSUE TITLE
Update values in results paragraph on steepness, replacement line

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/dogfish-assess#39]
Current paragraph:

> The unfished replacement line, i.e., pup survival, is \(1/\phi_0 = 0.44\) and the maximum steepness is 0.45. In comparison, the survival implied from the adult natural mortality rate is \(\exp(-M) = 0.93\). The \(z_\mathrm{frac} = 0.91\) could be an upper limit to the productivity of outside Dogfish where pup survival is equal to 0.93, as it is generally believed that juvenile survival does not exceed adult survival \citep{hoenig1990}.

around line 1066 in main.tex. Values may have changed.

Ideally include as \newcommands as elsewhere, but typing in is fine at this point too. Consider referencing a replacement line figure here too.

**Comment by quang-huynh** [comment]
Updated numbers can be obtained with `sapply(multi_rep, SS3_steep)`.

Here are the numbers for A0:

> The unfished replacement line, i.e., pup survival, is \(1/\phi_0 = 0.301\) and the maximum steepness is 0.663. In comparison, the survival implied from the adult natural mortality rate is \(\exp(-M) = 0.937\). The \(z_\mathrm{frac} = 0.91\) could be an upper limit to the productivity of outside Dogfish where pup survival is equal to 0.93, as it is generally believed that juvenile survival does not exceed adult survival \citep{hoenig1990}.

Regarding the second sentence (upper limit to zfrac), the model generates offspring which instantaneously experiences density dependent survival, then the age zero animals in the age structure experience the adult survival. In other words, even with zfrac = 1, age 0 survival does not exceed the adult survival, so the second sentence is irrelevant and not needed. 

Taylor et al 2013 p 16 writes

> The interpretation of the quantity z0 = –log(S0) as pre-recruit
instantaneous mortality rate at unfished equilibrium is imperfect
because the recruitment in a given year is calculated as a product
of the survival fraction Sy and the spawning output By for that same
time period so that there is not a 1-year lag between quantification
of eggs or pups and recruitment at age 0, which is when recruits
are calculated in Stock Synthesis. However, if age 0 or some set of
youngest ages is not selected by any fishery or survey, then density
dependent survival may be assumed to occur anywhere before the
first appearance of any cohort in the data or model expectations.
In such cases, the upper limit on survival up to age a is given by
Smaxe−aM.
